"""
executor.py · Execute (E in MAPE-K)

Responsibilities:
- Execute recovery actions generated by Planner
- Verify recovery success where possible
- Write audit records
- Trigger cooldowns
"""

from __future__ import annotations

import os
import smtplib
import time
from email.mime.text import MIMEText
from typing import Callable, Dict, Optional

import docker
import httpx
import paramiko

from config import AppConfig, Target
from knowledge import KnowledgeBase
from planner import ActionPlan


class ActionResult:
    def __init__(
        self,
        success: bool,
        duration_ms: int,
        error: Optional[str] = None,
    ):
        self.success = success
        self.duration_ms = duration_ms
        self.error = error


# ------------------------------------------------------------
# Helper
# ------------------------------------------------------------

def _get_target(
    target_name: str,
    config: AppConfig,
) -> Optional[Target]:
    return next(
        (
            t
            for t in config.targets
            if t.name == target_name or t.id == target_name
        ),
        None,
    )


def _ssh_run_command(
    target: Target,
    command: str,
) -> tuple[bool, str]:
    """
    Runs a command on an SSH target and returns:
    (success, combined_output)
    """
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(
        paramiko.AutoAddPolicy()
    )

    try:
        client.connect(
            hostname=target.host,
            username=target.username,
            key_filename=target.ssh_key,
            timeout=10,
        )

        stdin, stdout, stderr = client.exec_command(command)

        out = stdout.read().decode().strip()
        err = stderr.read().decode().strip()

        combined = "\n".join(
            x for x in [out, err] if x
        ).strip()

        exit_code = stdout.channel.recv_exit_status()

        return exit_code == 0, combined

    except Exception as e:
        return False, str(e)

    finally:
        client.close()


# ------------------------------------------------------------
# Recovery actions
# ------------------------------------------------------------

def restart_service(
    target_name: str,
    config: AppConfig,
) -> ActionResult:
    """
    Used mainly for local/docker targets such as bookshop.
    Restarts a configured Docker container and optionally
    verifies health_url recovery.
    """
    start = time.time()

    target = _get_target(target_name, config)
    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    try:
        if not target.container_name:
            return ActionResult(
                False,
                0,
                f"Target {target_name} has no container_name configured",
            )

        client = docker.from_env()
        container = client.containers.get(
            target.container_name
        )

        print(
            f"[Executor] Restarting container {target.container_name}",
            flush=True,
        )

        container.restart()

        # Optional health verification
        if target.health_url:
            for _ in range(30):
                time.sleep(1)

                try:
                    response = httpx.get(
                        target.health_url,
                        timeout=3,
                    )

                    if response.status_code == 200:
                        duration = int((time.time() - start) * 1000)
                        return ActionResult(True, duration)

                except Exception:
                    pass

            duration = int((time.time() - start) * 1000)
            return ActionResult(
                False,
                duration,
                "Health endpoint did not recover after restart",
            )

        duration = int((time.time() - start) * 1000)
        return ActionResult(True, duration)

    except Exception as e:
        duration = int((time.time() - start) * 1000)
        return ActionResult(False, duration, str(e))


def retry_http_endpoint(
    target_name: str,
    config: AppConfig,
) -> ActionResult:
    """
    Lightweight recovery / verification action:
    retries the health endpoint a few times.
    """
    start = time.time()

    target = _get_target(target_name, config)
    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    if not target.health_url:
        return ActionResult(
            False,
            0,
            f"Target {target_name} has no health_url configured",
        )

    delay = 1

    for _ in range(3):
        try:
            response = httpx.get(
                target.health_url,
                timeout=5,
            )

            if response.status_code == 200:
                duration = int((time.time() - start) * 1000)
                return ActionResult(True, duration)

        except Exception:
            pass

        time.sleep(delay)
        delay *= 2

    duration = int((time.time() - start) * 1000)
    return ActionResult(False, duration, "Endpoint retry failed")


def send_alert(
    target_name: str,
    config: AppConfig,
    message: str = "",
) -> ActionResult:
    """
    Sends alert via Slack/email if configured.
    Falls back to console alert if no channel configured.
    """
    start = time.time()
    sent = False

    if config.alerting.slack_webhook_url:
        try:
            payload = {
                "text": f"[Self-Healer] {target_name}\n{message}"
            }

            httpx.post(
                config.alerting.slack_webhook_url,
                json=payload,
                timeout=5,
            )
            sent = True

        except Exception as e:
            print(
                f"[Executor] Slack alert failed: {e}",
                flush=True,
            )

    if config.alerting.smtp_host and config.alerting.alert_email_to:
        try:
            msg = MIMEText(message)
            msg["Subject"] = f"[Self-Healer] Alert - {target_name}"
            msg["From"] = config.alerting.smtp_user
            msg["To"] = config.alerting.alert_email_to

            with smtplib.SMTP(
                config.alerting.smtp_host,
                config.alerting.smtp_port,
            ) as server:
                server.starttls()

                if config.alerting.smtp_user:
                    server.login(
                        config.alerting.smtp_user,
                        config.alerting.smtp_pass,
                    )

                server.send_message(msg)

            sent = True

        except Exception as e:
            print(
                f"[Executor] Email alert failed: {e}",
                flush=True,
            )

    if not sent:
        print(
            f"[ALERT] {target_name}: {message}",
            flush=True,
        )

    duration = int((time.time() - start) * 1000)
    return ActionResult(True, duration)


def rotate_log(
    target_name: str,
    config: AppConfig,
) -> ActionResult:
    """
    Local log rotation:
    renames current log file to a timestamped backup
    and creates a fresh empty log file.
    """
    start = time.time()

    target = _get_target(target_name, config)
    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    log_path = target.log_path

    if not log_path:
        return ActionResult(
            False,
            0,
            f"Target {target_name} has no log_path configured",
        )

    try:
        backup_file = f"{log_path}.bak.{int(time.time())}"

        os.rename(log_path, backup_file)
        open(log_path, "w").close()

        duration = int((time.time() - start) * 1000)
        return ActionResult(True, duration)

    except Exception as e:
        duration = int((time.time() - start) * 1000)
        return ActionResult(False, duration, str(e))


def restart_process(
    target_name: str,
    config: AppConfig,
) -> ActionResult:
    """
    SSH demo healing action:
    runs the configured restart_command on the remote WSL demo target.

    Example:
        bash /home/hpsomeel/healer_demo_lab/restart_dummy.sh
    """
    start = time.time()

    target = _get_target(target_name, config)
    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    if not target.is_ssh:
        return ActionResult(
            False,
            0,
            f"restart_process only supports SSH targets, got {target.type}",
        )

    if not target.restart_command:
        return ActionResult(
            False,
            0,
            f"Target {target_name} has no restart_command configured",
        )

    print(
        f"[Executor] SSH restart_process on {target.name}: {target.restart_command}",
        flush=True,
    )

    ok, output = _ssh_run_command(
        target,
        target.restart_command,
    )

    duration = int((time.time() - start) * 1000)

    if not ok:
        return ActionResult(
            False,
            duration,
            output or "restart_process failed",
        )

    # Optional verification
    if target.process_name:
        verify_cmd = (
            f"pgrep -f '{target.process_name}' >/dev/null && "
            f"echo RUNNING || echo STOPPED"
        )

        verify_ok, verify_output = _ssh_run_command(
            target,
            verify_cmd,
        )

        if not verify_ok or verify_output.strip() != "RUNNING":
            return ActionResult(
                False,
                duration,
                f"Restart command ran but process verification failed: {verify_output}",
            )

    return ActionResult(True, duration)


def cleanup_demo(
    target_name: str,
    config: AppConfig,
) -> ActionResult:
    """
    SSH demo cleanup action:
    runs the configured cleanup_command on the remote WSL demo target.

    Intended for safe HIGH_CPU / HIGH_RAM handling in the demo lab.
    Example:
        bash /home/hpsomeel/healer_demo_lab/cleanup_demo.sh
    """
    start = time.time()

    target = _get_target(target_name, config)
    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    if not target.is_ssh:
        return ActionResult(
            False,
            0,
            f"cleanup_demo only supports SSH targets, got {target.type}",
        )

    if not target.cleanup_command:
        return ActionResult(
            False,
            0,
            f"Target {target_name} has no cleanup_command configured",
        )

    print(
        f"[Executor] SSH cleanup_demo on {target.name}: {target.cleanup_command}",
        flush=True,
    )

    ok, output = _ssh_run_command(
        target,
        target.cleanup_command,
    )

    duration = int((time.time() - start) * 1000)

    if not ok:
        return ActionResult(
            False,
            duration,
            output or "cleanup_demo failed",
        )

    return ActionResult(True, duration)


ACTION_REGISTRY: Dict[str, Callable] = {
    "restart_service": restart_service,
    "retry_http_endpoint": retry_http_endpoint,
    "send_alert": send_alert,
    "rotate_log": rotate_log,
    "restart_process": restart_process,
    "cleanup_demo": cleanup_demo,
}


# ------------------------------------------------------------
# Executor
# ------------------------------------------------------------

class Executor:
    def __init__(
        self,
        config: AppConfig,
        kb: KnowledgeBase,
    ):
        self.config = config
        self.kb = kb

    def execute(
        self,
        plan: ActionPlan,
    ) -> list[ActionResult]:

        results: list[ActionResult] = []
        anomaly = plan.anomaly

        self.kb.update_incident_status(
            anomaly.target_name,
            anomaly.anomaly_type,
            "IN_PROGRESS",
        )

        alert_message = (
            f"Anomaly: {anomaly.anomaly_type}\n"
            f"Severity: {anomaly.severity}\n"
            f"Target: {anomaly.target_name}\n"
            f"Value: {anomaly.metric_value}\n"
            f"Context: {anomaly.context}"
        )

        overall_success = True

        for action_name in plan.actions:
            action_fn = ACTION_REGISTRY.get(action_name)

            if not action_fn:
                print(
                    f"[Executor] Unknown action: {action_name}",
                    flush=True,
                )

                result = ActionResult(
                    False,
                    0,
                    f"Unknown action: {action_name}",
                )

                self.kb.write_audit(
                    target_name=anomaly.target_name,
                    anomaly_type=anomaly.anomaly_type,
                    action=action_name,
                    success=False,
                    duration_ms=0,
                    error_msg=result.error,
                )

                results.append(result)
                overall_success = False
                continue

            print(
                f"[Executor] Running {action_name} on {anomaly.target_name}",
                flush=True,
            )

            try:
                if action_name == "send_alert":
                    result = action_fn(
                        anomaly.target_name,
                        self.config,
                        alert_message,
                    )
                else:
                    result = action_fn(
                        anomaly.target_name,
                        self.config,
                    )

            except Exception as e:
                result = ActionResult(
                    False,
                    0,
                    str(e),
                )

            self.kb.write_audit(
                target_name=anomaly.target_name,
                anomaly_type=anomaly.anomaly_type,
                action=action_name,
                success=result.success,
                duration_ms=result.duration_ms,
                error_msg=result.error,
            )

            results.append(result)

            if not result.success:
                overall_success = False

            print(
                f"[Executor] {action_name} -> "
                f"{'SUCCESS' if result.success else 'FAILED'} "
                f"({result.duration_ms} ms)",
                flush=True,
            )

        # --------------------------------------------------------
        # Final incident / cooldown handling
        # --------------------------------------------------------
        if overall_success:
            self.kb.update_incident_status(
                anomaly.target_name,
                anomaly.anomaly_type,
                "RESOLVED",
            )

            self.kb.resolve_incident(
                anomaly.target_name,
                anomaly.anomaly_type,
            )

            cooldown_key = plan.metadata.get(
                "cooldown_key",
                f"{anomaly.target_name}:{anomaly.anomaly_type}",
            )

            rule = self.config.rule_for(anomaly.anomaly_type)
            cooldown_minutes = rule.cooldown_minutes if rule else 1
            cooldown_seconds = max(1, cooldown_minutes * 60)

            self.kb.set_cooldown(
                cooldown_key,
                cooldown_seconds,
            )

        else:
            self.kb.update_incident_status(
                anomaly.target_name,
                anomaly.anomaly_type,
                "FAILED",
            )

        return results