"""
executor.py · Execute (E in MAPE-K)

Responsibilities:
- Execute recovery actions generated by Planner
- Verify recovery success
- Write audit records
- Trigger cooldowns
"""

from __future__ import annotations

import os
import smtplib
import time
from email.mime.text import MIMEText
from typing import Dict, Optional

import docker
import httpx

from config import AppConfig
from knowledge import KnowledgeBase
from planner import ActionPlan


class ActionResult:

    def __init__(
        self,
        success: bool,
        duration_ms: int,
        error: Optional[str] = None,
    ):
        self.success = success
        self.duration_ms = duration_ms
        self.error = error


def restart_service(
    target_name: str,
    config: AppConfig,
) -> ActionResult:

    start = time.time()

    target = next(
        (
            t
            for t in config.targets
            if t.name == target_name
        ),
        None,
    )

    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    try:

        client = docker.from_env()

        container = client.containers.get(
            target.container_name
        )

        print(
            f"[Executor] Restarting container "
            f"{target.container_name}",
            flush=True,
        )

        container.restart()

        for _ in range(30):

            time.sleep(1)

            try:

                response = httpx.get(
                    target.health_url,
                    timeout=3,
                )

                if response.status_code == 200:

                    duration = int(
                        (time.time() - start)
                        * 1000
                    )

                    return ActionResult(
                        True,
                        duration,
                    )

            except Exception:
                pass

        duration = int(
            (time.time() - start)
            * 1000
        )

        return ActionResult(
            False,
            duration,
            "Health endpoint did not recover",
        )

    except Exception as e:

        duration = int(
            (time.time() - start)
            * 1000
        )

        return ActionResult(
            False,
            duration,
            str(e),
        )


def retry_http_endpoint(
    target_name: str,
    config: AppConfig,
) -> ActionResult:

    start = time.time()

    target = next(
        (
            t
            for t in config.targets
            if t.name == target_name
        ),
        None,
    )

    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    delay = 1

    for _ in range(3):

        try:

            response = httpx.get(
                target.health_url,
                timeout=5,
            )

            if response.status_code == 200:

                duration = int(
                    (time.time() - start)
                    * 1000
                )

                return ActionResult(
                    True,
                    duration,
                )

        except Exception:
            pass

        time.sleep(delay)
        delay *= 2

    duration = int(
        (time.time() - start)
        * 1000
    )

    return ActionResult(
        False,
        duration,
        "Endpoint retry failed",
    )


def send_alert(
    target_name: str,
    config: AppConfig,
    message: str = "",
) -> ActionResult:

    start = time.time()

    sent = False

    if config.alerting.slack_webhook_url:

        try:

            payload = {
                "text":
                f"[Self-Healer] {target_name}\n{message}"
            }

            httpx.post(
                config.alerting.slack_webhook_url,
                json=payload,
                timeout=5,
            )

            sent = True

        except Exception as e:

            print(
                f"[Executor] Slack alert failed: {e}",
                flush=True,
            )

    if (
        config.alerting.smtp_host
        and config.alerting.alert_email_to
    ):

        try:

            msg = MIMEText(message)

            msg["Subject"] = (
                f"[Self-Healer] Alert - "
                f"{target_name}"
            )

            msg["From"] = (
                config.alerting.smtp_user
            )

            msg["To"] = (
                config.alerting.alert_email_to
            )

            with smtplib.SMTP(
                config.alerting.smtp_host,
                config.alerting.smtp_port,
            ) as server:

                server.starttls()

                if config.alerting.smtp_user:

                    server.login(
                        config.alerting.smtp_user,
                        config.alerting.smtp_pass,
                    )

                server.send_message(msg)

            sent = True

        except Exception as e:

            print(
                f"[Executor] Email alert failed: {e}",
                flush=True,
            )

    if not sent:

        print(
            f"[ALERT] {target_name}: {message}",
            flush=True,
        )

    duration = int(
        (time.time() - start)
        * 1000
    )

    return ActionResult(
        True,
        duration,
    )


def rotate_log(
    target_name: str,
    config: AppConfig,
) -> ActionResult:

    start = time.time()

    target = next(
        (
            t
            for t in config.targets
            if t.name == target_name
        ),
        None,
    )

    if not target:
        return ActionResult(
            False,
            0,
            f"Unknown target: {target_name}",
        )

    try:

        backup_file = (
            f"{target.log_path}"
            f".bak.{int(time.time())}"
        )

        os.rename(
            target.log_path,
            backup_file,
        )

        open(
            target.log_path,
            "w",
        ).close()

        duration = int(
            (time.time() - start)
            * 1000
        )

        return ActionResult(
            True,
            duration,
        )

    except Exception as e:

        duration = int(
            (time.time() - start)
            * 1000
        )

        return ActionResult(
            False,
            duration,
            str(e),
        )


ACTION_REGISTRY: Dict[str, callable] = {
    "restart_service": restart_service,
    "retry_http_endpoint": retry_http_endpoint,
    "send_alert": send_alert,
    "rotate_log": rotate_log,
}


class Executor:

    def __init__(
        self,
        config: AppConfig,
        kb: KnowledgeBase,
    ):
        self.config = config
        self.kb = kb

    def execute(
        self,
        plan: ActionPlan,
    ) -> list[ActionResult]:

        results = []

        anomaly = plan.anomaly

        alert_message = (
            f"Anomaly: {anomaly.anomaly_type}\n"
            f"Severity: {anomaly.severity}\n"
            f"Target: {anomaly.target_name}\n"
            f"Value: {anomaly.metric_value}\n"
            f"Context: {anomaly.context}"
        )

        for action_name in plan.actions:

            action_fn = ACTION_REGISTRY.get(
                action_name
            )

            if not action_fn:

                print(
                    f"[Executor] Unknown action: "
                    f"{action_name}",
                    flush=True,
                )

                continue

            print(
                f"[Executor] Running "
                f"{action_name} "
                f"on "
                f"{anomaly.target_name}",
                flush=True,
            )

            try:

                if action_name == "send_alert":

                    result = action_fn(
                        anomaly.target_name,
                        self.config,
                        alert_message,
                    )

                else:

                    result = action_fn(
                        anomaly.target_name,
                        self.config,
                    )

            except Exception as e:

                result = ActionResult(
                    False,
                    0,
                    str(e),
                )

            self.kb.write_audit(
                target_name=anomaly.target_name,
                anomaly_type=anomaly.anomaly_type,
                action=action_name,
                success=result.success,
                duration_ms=result.duration_ms,
                error_msg=result.error,
            )

            results.append(result)

            print(
                f"[Executor] "
                f"{action_name} -> "
                f"{'SUCCESS' if result.success else 'FAILED'} "
                f"({result.duration_ms} ms)",
                flush=True,
            )

        return results