services:
  bookshop:
    build: ./bookshop
    container_name: bookshop
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/var/log/bookshop
    restart: "no"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node-exporter
      - bookshop
    restart: "no"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: "no"

  healer:
    build: ./self_healer
    container_name: healer
    ports:
      - "8000:8000"
    volumes:
      - ./self_healer:/app
      - ./logs:/var/log/bookshop
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/Hp/.ssh:/root/.ssh:ro
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - bookshop
      - prometheus
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
    restart: "no"

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - healer
    restart: "no"